languageCode = "fr"
languageName = "Français"
displayName = "FR"
isoCode = "fr"
weight = 3
rtl = false
contentDir = 'content/fr'

title = "Blowfish"
# logo = "img/logo.png"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Your name here"
  image = "img/fotoperfil.jpg"
  headline = "I'm only human"
  bio = "A little bit about you"
  links = [
    { github = "https://github.com/username" },
    { linkedin = "https://linkedin.com/in/username" },
  ]
