languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 2
rtl = false
contentDir = 'content/en'

title = "TareaHugo"
# logo = "img/logo.png"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Mikelangelo"
  image = "img/fotoperfil.jpg"
  headline = "Student at CPIFP Los Enlaces"
  bio = "A little bit about you"
  links = [
    { github = "https://github.com/username" },
    { linkedin = "https://linkedin.com/in/username" },
  ]


