languageCode = "es"
languageName = "Español"
displayName = "ES"
isoCode = "es"
weight = 1
rtl = false
contentDir = 'content/es'

title = "TareaHugo"
# logo = "img/logo.png"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Mikelangelo"
  image = "img/fotoperfil.jpg"
  headline = "Estudiante en CPIFP Los Enlaces"
  bio = "A little bit about you"
  links = [
    { github = "https://github.com/username" },
    { linkedin = "https://linkedin.com/in/username" },
  ]

